/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

const fileMap = {
  
  "clients.baml": "client<llm> Gemini {\n  provider google-ai\n  retry_policy Exponential\n  options {\n    model \"gemini-3-flash-preview\"\n    api_key env.GOOGLE_API_KEY\n  }\n}\n\nretry_policy Exponential {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 300\n    multiplier 1.5\n    max_delay_ms 10000\n  }\n}\n",
  "generators.baml": "generator target {\n  output_type \"typescript\"\n  output_dir \"../src/lib\"\n  version \"0.223.0\"\n  default_client_mode async\n}\n",
  "receipts.baml": "class ReceiptItem {\n  name string\n  quantity float\n  unitPrice float\n  totalPrice float\n  vatRate float\n}\n\nclass Receipt {\n  qrCode string? @description(\"The full QR code content (URL or ID starting with O-). Look for the eKasa QR code, usually at the bottom of the receipt.\")\n  supplierName string? @description(\"Name of the store or supplier\")\n  supplierVatId string? @description(\"VAT ID (IC DPH) of the supplier\")\n  totalAmount float @description(\"Total amount paid\")\n  currency string @description(\"Currency code (e.g. EUR)\")\n  issueDate string? @description(\"Date of issue in ISO format YYYY-MM-DD\")\n  items ReceiptItem[]\n}\n\nfunction ExtractReceipt(receiptImage: image) -> Receipt {\n  client Gemini\n  prompt #\"\n    Extract data from this receipt.\n\n    If there is a QR code (usually at the bottom), try to decode it.\n    The QR code for Slovak eKasa usually contains a long ID starting with 'O-' or 'V-'.\n\n    {{ receiptImage }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}
export const getBamlFiles = () => {
    return fileMap;
}